{% set name = "elapid" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  # Uncomment the following line if the package is pure Python and the recipe
  # is exactly the same for all platforms. It is okay if the dependencies are
  # not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python
  # for more details.
  noarch: python

  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  # If the installation is complex, or different between Unix and Windows,
  # use separate bld.bat and build.sh files instead of this key. By default,
  # the package will be built for the Python versions supported by conda-forge
  # and for all major OSs. Add the line "skip: True  # [py<35]" (for example)
  # to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit
  # to Windows.
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required
    # compilers as separate entries here. Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('fortran') }}
  host:
    - python >=3.7,<3.9
    - pip
  run:
    - python >=3.7,<3.9
    - descartes >=1.1.0
    - geopandas >=0.7.0
    - glmnet >=2.2.0
    - pandas >=1.0.3
    - rasterio >=1.2.1
    - rtree
    - scikit-learn >=0.22.2
    - shapely >=1.7.0
    - tqdm >=4.60.0


test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - elapid
  # Run your test commands here
  commands:
    - pytest
  # declare any test-only requirements here
  requires:
    - pytest
    - pytest-cov
  # copy over any needed test files here
  source_files:
    - tests/

about:
  home: https://elapid.org
  license: MIT
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - earth-chris
