name: deploy-docs

on:
  workflow_run:
    branches: [ "main" ]
    workflows: ["run-pytest"]
    types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pixi
        with:
          environments: docs
      - run: pixi run -e docs deploy-docs
