name: run-condatest

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    env:
      PYTHON_VERSION: 3.8
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Fix conda permissions on mac
      run: sudo chown -R $UID $CONDA
      if: ${{ matrix.os }} == 'macos-latest'
    - name: Install dependencies
      run: |
        make init
    - name: Run pytest
      run: |
        make test
