name: run-pytest

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        environment: [dev, dev-py312, dev-py313]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-pixi
      with:
        environments: ${{ matrix.environment }}
    - name: Run pytest
      run: pixi run -e ${{ matrix.environment }} test --cov-report=xml:coverage.xml
    - name: Run ruff
      run: pixi run -e ${{ matrix.environment }} lint
